version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - dbdata:/var/opt/mssql

  identity-server:
    build:
      context: ../../
      dockerfile: templates/service/host/IdentityServerHost/Dockerfile
    depends_on:
      - sqlserver
  
  bank-management:
    build:
      context: ../../
      dockerfile: templates/service/host/BankManagement.Host/Dockerfile
    depends_on:
      - sqlserver
      - identity-server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - xpack.security.transport.ssl.enabled=false
    - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - 5601:5601

volumes:
  dbdata:
